export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const REMOVE_AUTH_ERROR = 'REMOVE_AUTH_ERROR';
export const FETCH_MESSAGE = 'FETCH_MESSAGE';
export const GET_PROFILE = 'GET_PROFILE';

export const CREATE_STORY = 'CREATE_STORY';
export const GET_STORIES = 'GET_STORIES';
export const GET_STORY = 'GET_STORY';
export const STORY_TO_NULL = 'STORY_TO_NULL';

export const CREATE_OPPORTUNITY = 'CREATE_OPPORTUNITY';
export const GET_OPPORTUNITIES = 'GET_OPPORTUNITIES';
export const GET_OPPORTUNITY = 'GET_OPPORTUNITY';
export const GET_MY_OPPORTUNITIES = 'GET_MY_OPPORTUNITIES';
export const CURRENT_OPPORTUNITY_TO_NULL = 'CURRENT_OPPORTUNITY_TO_NULL';
export const IS_CREATOR = 'IS_CREATOR';
export const CREATOR_TO_FALSE  = 'CREATOR_TO_FALSE';

export const CREATE_OPPORTUNITY_APPLICATION = 'CREATE_OPPORTUNITY_APPLICATION';
export const MY_APPLIED_POSITIONS = 'MY_APPLIED_POSITIONS';
